export const POSTS_REQUESTED = 'POSTS_REQUESTED';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';

export const MODAL_REGISTRATION = 'MODAL_REGISTRATION';
export const MODAL_AUTOROTATION = 'MODAL_AUTOROTATION';
export const MODAL_CLOSE = 'MODAL_CLOSE';
