export const POSTS_REQUESTED = 'POSTS_REQUESTED';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';
export const TOGGLE_POST_MODAL = 'TOGGLE_POST_MODAL';
export const CREATE_POST_REQUESTED = 'CREATE_POSTS_REQUESTED';
export const CREATE_POST_RECEIVED = 'CREATE_POST_RECEIVED';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
export const CHANGE_USER_REQUESTED = 'CHANGE_USER_REQUESTED';
export const CHANGE_USER_RECEIVED = 'CHANGE_USER_RECEIVED';
export const SAVE_QUERY_PARAMS = 'SAVE_QUERY_PARAMS';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const USER_DATA = 'USER_DATA';
export const AUTH_RECEIVED = 'AUTH_RECEIVED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const USER_DATA_AUTH_REQUESTED = 'USER_DATA_AUTH_REQUESTED';
export const USER_DATA_REQUESTED = 'USER_DATA_REQUESTED';
export const USER_DATA_AUTH_RECEIVED = 'USER_DATA_AUTH_RECEIVED';
export const USER_DATA_RECEIVED = 'USER_DATA_RECEIVED';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';

export const SIGN_IN = 'Sign In';
export const SIGN_UP = 'Sign Up';

export const ROUT_TO_MAIN = '/';
export const ROUT_TO_USER = 'user';

export const URL_FOR_POST = '/posts';
